2023-12-05 17:28:56,607 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:28:56,608 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/giZYlHwKND
2023-12-05 17:28:56,608 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/giZYlHwKND
2023-12-05 17:28:56,608 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:28:56,608 - INFO - Starting Flet View app...
2023-12-05 17:28:56,608 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:28:56,809 - INFO - Session started: 
2023-12-05 17:51:39,002 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:51:39,003 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/IjSCiOXnjH
2023-12-05 17:51:39,003 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/IjSCiOXnjH
2023-12-05 17:51:39,004 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:51:39,004 - INFO - Starting Flet View app...
2023-12-05 17:51:39,004 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:51:39,260 - INFO - Session started: 
2023-12-05 17:51:45,629 - ERROR - TipsViewWithBackButton.process() missing 1 required positional argument: 'page'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: TipsViewWithBackButton.process() missing 1 required positional argument: 'page'
2023-12-05 17:52:06,400 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:52:06,401 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/RJFSbaMItv
2023-12-05 17:52:06,401 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/RJFSbaMItv
2023-12-05 17:52:06,401 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:52:06,401 - INFO - Starting Flet View app...
2023-12-05 17:52:06,401 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:52:06,608 - INFO - Session started: 
2023-12-05 17:52:08,520 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 17:52:10,005 - ERROR - unsupported operand type(s) for +: 'View' and 'str'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/_build_in_b.py", line 16, in process
    url = page.views[-1] + "/tips"
          ~~~~~~~~~~~~~~~^~~~~~~~~
TypeError: unsupported operand type(s) for +: 'View' and 'str'
2023-12-05 17:52:28,074 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:52:28,075 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/rGWvfCGcDH
2023-12-05 17:52:28,075 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/rGWvfCGcDH
2023-12-05 17:52:28,075 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:52:28,075 - INFO - Starting Flet View app...
2023-12-05 17:52:28,075 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:52:28,283 - INFO - Session started: 
2023-12-05 17:52:30,184 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 17:53:00,915 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:53:00,916 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ZKLEKVwjDK
2023-12-05 17:53:00,916 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ZKLEKVwjDK
2023-12-05 17:53:00,916 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:53:00,917 - INFO - Starting Flet View app...
2023-12-05 17:53:00,917 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:53:01,116 - INFO - Session started: 
2023-12-05 17:55:14,254 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 17:55:14,255 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/gbwHaxHTFX
2023-12-05 17:55:14,255 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/gbwHaxHTFX
2023-12-05 17:55:14,255 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 17:55:14,255 - INFO - Starting Flet View app...
2023-12-05 17:55:14,255 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 17:55:14,463 - INFO - Session started: 
2023-12-05 17:55:16,385 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 18:44:20,226 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 18:44:20,227 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/envbAGcXrF
2023-12-05 18:44:20,227 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/envbAGcXrF
2023-12-05 18:44:20,227 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 18:44:20,228 - INFO - Starting Flet View app...
2023-12-05 18:44:20,228 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 18:44:20,472 - INFO - Session started: 
2023-12-05 18:44:48,598 - ERROR - 'list_iterator' object has no attribute 'keys'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugins.py", line 234, in process
    columns = data.keys
              ^^^^^^^^^
AttributeError: 'list_iterator' object has no attribute 'keys'
2023-12-05 18:47:43,619 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 18:51:11,797 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 18:51:11,798 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/KJeJfAgiqm
2023-12-05 18:51:11,798 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/KJeJfAgiqm
2023-12-05 18:51:11,798 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 18:51:11,798 - INFO - Starting Flet View app...
2023-12-05 18:51:11,798 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 18:51:12,012 - INFO - Session started: 
2023-12-05 19:05:08,480 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:05:08,480 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/lczRLYYUjl
2023-12-05 19:05:08,481 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/lczRLYYUjl
2023-12-05 19:05:08,481 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:05:08,481 - INFO - Starting Flet View app...
2023-12-05 19:05:08,481 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:05:08,708 - INFO - Session started: 
2023-12-05 19:08:48,590 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:08:48,592 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/EiPMPnJMzU
2023-12-05 19:08:48,592 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/EiPMPnJMzU
2023-12-05 19:08:48,592 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:08:48,592 - INFO - Starting Flet View app...
2023-12-05 19:08:48,592 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:08:48,787 - INFO - Session started: 
2023-12-05 19:08:51,446 - ERROR - name 'partial' is not defined
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/_base.py", line 73, in process
    func = partial(
           ^^^^^^^
NameError: name 'partial' is not defined
2023-12-05 19:19:43,360 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:19:43,362 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/yLNltOoXyB
2023-12-05 19:19:43,362 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/yLNltOoXyB
2023-12-05 19:19:43,362 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:19:43,362 - INFO - Starting Flet View app...
2023-12-05 19:19:43,363 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:19:43,578 - INFO - Session started: 
2023-12-05 19:19:43,578 - ERROR - '_index'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 30, in run
    plugin = icls.PLUGINS[plugin_name]
             ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '_index'
2023-12-05 19:22:31,689 - ERROR - [Errno 2] No such file or directory: ''
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 123, in process
    self._load("", path=data)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 128, in _load
    for item in os.listdir(f):
                ^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''
2023-12-05 19:22:31,690 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:22:31,691 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/tDyDizwhZV
2023-12-05 19:22:31,692 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/tDyDizwhZV
2023-12-05 19:22:31,692 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:22:31,692 - INFO - Starting Flet View app...
2023-12-05 19:22:31,692 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:22:31,899 - INFO - Session started: 
2023-12-05 19:22:31,899 - ERROR - '_index'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 30, in run
    plugin = icls.PLUGINS[plugin_name]
             ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '_index'
2023-12-05 19:24:21,920 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:24:21,920 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/sUAIoKvuxv
2023-12-05 19:24:21,921 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/sUAIoKvuxv
2023-12-05 19:24:21,921 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:24:21,921 - INFO - Starting Flet View app...
2023-12-05 19:24:21,921 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:24:22,132 - INFO - Session started: 
2023-12-05 19:24:32,038 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins/plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 19:25:18,747 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:25:18,747 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/zzdCkCKyrC
2023-12-05 19:25:18,747 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/zzdCkCKyrC
2023-12-05 19:25:18,747 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:25:18,747 - INFO - Starting Flet View app...
2023-12-05 19:25:18,747 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:25:18,960 - INFO - Session started: 
2023-12-05 19:25:18,960 - ERROR - '_index'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 30, in run
    plugin = icls.PLUGINS[plugin_name]
             ~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: '_index'
2023-12-05 19:27:54,307 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:27:54,308 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/aMSFfSbQvo
2023-12-05 19:27:54,309 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/aMSFfSbQvo
2023-12-05 19:27:54,309 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:27:54,309 - INFO - Starting Flet View app...
2023-12-05 19:27:54,309 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:27:54,502 - INFO - Session started: 
2023-12-05 19:32:42,939 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:32:42,940 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/VeaPgrgHWS
2023-12-05 19:32:42,940 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/VeaPgrgHWS
2023-12-05 19:32:42,940 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:32:42,940 - INFO - Starting Flet View app...
2023-12-05 19:32:42,940 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:32:43,205 - INFO - Session started: 
2023-12-05 19:33:00,355 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:33:00,356 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/vzfxmXjKJb
2023-12-05 19:33:00,356 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/vzfxmXjKJb
2023-12-05 19:33:00,356 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:33:00,356 - INFO - Starting Flet View app...
2023-12-05 19:33:00,357 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:33:00,572 - INFO - Session started: 
2023-12-05 19:33:38,331 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:33:38,331 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ntAZgfaqRN
2023-12-05 19:33:38,331 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ntAZgfaqRN
2023-12-05 19:33:38,331 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:33:38,331 - INFO - Starting Flet View app...
2023-12-05 19:33:38,332 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:33:38,543 - INFO - Session started: 
2023-12-05 19:35:40,639 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 19:35:40,640 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/SHEBacCHls
2023-12-05 19:35:40,640 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/SHEBacCHls
2023-12-05 19:35:40,640 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 19:35:40,640 - INFO - Starting Flet View app...
2023-12-05 19:35:40,640 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 19:35:40,920 - INFO - Session started: 
2023-12-05 20:13:32,332 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:13:32,333 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/bWZpWKMxbJ
2023-12-05 20:13:32,333 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/bWZpWKMxbJ
2023-12-05 20:13:32,333 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:13:32,333 - INFO - Starting Flet View app...
2023-12-05 20:13:32,333 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:13:32,584 - INFO - Session started: 
2023-12-05 20:20:38,076 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:20:38,077 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/jTExLyJsgJ
2023-12-05 20:20:38,077 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/jTExLyJsgJ
2023-12-05 20:20:38,077 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:20:38,077 - INFO - Starting Flet View app...
2023-12-05 20:20:38,078 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:20:38,313 - INFO - Session started: 
2023-12-05 20:20:41,600 - ERROR - cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 97, in process
    rows, columns = self._rebuild_data(rows, columns)
    ^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
2023-12-05 20:21:18,781 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:21:18,782 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/dJTmVQItuB
2023-12-05 20:21:18,783 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/dJTmVQItuB
2023-12-05 20:21:18,783 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:21:18,783 - INFO - Starting Flet View app...
2023-12-05 20:21:18,784 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:21:18,983 - INFO - Session started: 
2023-12-05 20:22:08,948 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:22:08,950 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/hmwMmmiksh
2023-12-05 20:22:08,950 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/hmwMmmiksh
2023-12-05 20:22:08,951 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:22:08,951 - INFO - Starting Flet View app...
2023-12-05 20:22:08,951 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:22:09,166 - INFO - Session started: 
2023-12-05 20:23:07,936 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:23:07,937 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/pdEVKwNHdO
2023-12-05 20:23:07,937 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/pdEVKwNHdO
2023-12-05 20:23:07,937 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:23:07,937 - INFO - Starting Flet View app...
2023-12-05 20:23:07,937 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:23:08,158 - INFO - Session started: 
2023-12-05 20:23:44,214 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:23:44,214 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/GzZFXfNmqB
2023-12-05 20:23:44,215 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/GzZFXfNmqB
2023-12-05 20:23:44,215 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:23:44,215 - INFO - Starting Flet View app...
2023-12-05 20:23:44,216 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:23:44,431 - INFO - Session started: 
2023-12-05 20:25:03,609 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:25:03,609 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/iyLqiSEAje
2023-12-05 20:25:03,610 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/iyLqiSEAje
2023-12-05 20:25:03,610 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:25:03,610 - INFO - Starting Flet View app...
2023-12-05 20:25:03,610 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:25:03,824 - INFO - Session started: 
2023-12-05 20:29:00,121 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:29:00,121 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/MVwjkvEhYw
2023-12-05 20:29:00,122 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/MVwjkvEhYw
2023-12-05 20:29:00,122 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:29:00,122 - INFO - Starting Flet View app...
2023-12-05 20:29:00,122 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:29:00,335 - INFO - Session started: 
2023-12-05 20:32:32,523 - ERROR - Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 124, in process
    self._load("", path=data)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 137, in _load
    loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 204, in <module>
    class SearchBase(UIPlugin):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 219, in SearchBase
    def tips_edit(self, e, container=ft.Container(), page=ft.Page()):
                                                          ^^^^^^^^^
TypeError: Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
2023-12-05 20:32:32,523 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:32:32,524 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ZabMiEAvRv
2023-12-05 20:32:32,524 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ZabMiEAvRv
2023-12-05 20:32:32,524 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:32:32,524 - INFO - Starting Flet View app...
2023-12-05 20:32:32,524 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:32:32,736 - INFO - Session started: 
2023-12-05 20:32:44,637 - ERROR - Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 124, in process
    self._load("", path=data)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 137, in _load
    loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 204, in <module>
    class SearchBase(UIPlugin):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 219, in SearchBase
    def tips_edit(self, e, container=ft.Container(), page=ft.Page()):
                                                          ^^^^^^^^^
TypeError: Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
2023-12-05 20:32:44,638 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:32:44,638 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/pkSZADCVXt
2023-12-05 20:32:44,638 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/pkSZADCVXt
2023-12-05 20:32:44,638 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:32:44,638 - INFO - Starting Flet View app...
2023-12-05 20:32:44,638 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:32:44,842 - INFO - Session started: 
2023-12-05 20:32:46,733 - ERROR - Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 124, in process
    self._load("", path=data)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 137, in _load
    loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 204, in <module>
    class SearchBase(UIPlugin):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 219, in SearchBase
    def tips_edit(self, e, container=ft.Container(), page=ft.Page()):
                                                          ^^^^^^^^^
TypeError: Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
2023-12-05 20:32:47,474 - ERROR - Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 124, in process
    self._load("", path=data)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 133, in _load
    self._load(item, full_path)
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 137, in _load
    loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 605, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1120, in load_module
  File "<frozen importlib._bootstrap_external>", line 945, in load_module
  File "<frozen importlib._bootstrap>", line 290, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 721, in _load
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 204, in <module>
    class SearchBase(UIPlugin):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_ui.py", line 219, in SearchBase
    def tips_edit(self, e, container=ft.Container(), page=ft.Page()):
                                                          ^^^^^^^^^
TypeError: Page.__init__() missing 2 required positional arguments: 'conn' and 'session_id'
2023-12-05 20:33:31,506 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:33:31,507 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/RtbJoOdJXV
2023-12-05 20:33:31,507 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/RtbJoOdJXV
2023-12-05 20:33:31,507 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:33:31,507 - INFO - Starting Flet View app...
2023-12-05 20:33:31,508 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:33:31,706 - INFO - Session started: 
2023-12-05 20:33:50,873 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 20:33:50,874 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ACyBHmWLin
2023-12-05 20:33:50,875 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/ACyBHmWLin
2023-12-05 20:33:50,875 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 20:33:50,875 - INFO - Starting Flet View app...
2023-12-05 20:33:50,875 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 20:33:51,085 - INFO - Session started: 
2023-12-05 22:25:14,254 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:25:14,254 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/mIAOyJQEqv
2023-12-05 22:25:14,254 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/mIAOyJQEqv
2023-12-05 22:25:14,254 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:25:14,255 - INFO - Starting Flet View app...
2023-12-05 22:25:14,255 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:25:14,465 - INFO - Session started: 
2023-12-05 22:28:53,539 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:28:53,539 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/QLKalghJId
2023-12-05 22:28:53,540 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/QLKalghJId
2023-12-05 22:28:53,540 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:28:53,540 - INFO - Starting Flet View app...
2023-12-05 22:28:53,540 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:28:53,749 - INFO - Session started: 
2023-12-05 22:29:43,597 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:29:43,598 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/oUJPYVsILb
2023-12-05 22:29:43,598 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/oUJPYVsILb
2023-12-05 22:29:43,598 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:29:43,599 - INFO - Starting Flet View app...
2023-12-05 22:29:43,599 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:29:43,819 - INFO - Session started: 
2023-12-05 22:33:40,043 - ERROR - SearchBase.process() missing 1 required positional argument: 'tips_btn'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SearchBase.process() missing 1 required positional argument: 'tips_btn'
2023-12-05 22:34:41,922 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:34:41,924 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/UnZZFGQsXW
2023-12-05 22:34:41,924 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/UnZZFGQsXW
2023-12-05 22:34:41,924 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:34:41,924 - INFO - Starting Flet View app...
2023-12-05 22:34:41,924 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:34:42,148 - INFO - Session started: 
2023-12-05 22:35:07,402 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:35:07,403 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/tPGsBdopKb
2023-12-05 22:35:07,403 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/tPGsBdopKb
2023-12-05 22:35:07,403 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:35:07,403 - INFO - Starting Flet View app...
2023-12-05 22:35:07,404 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:35:07,621 - INFO - Session started: 
2023-12-05 22:35:09,497 - ERROR - 'str' object has no attribute '_build_add_commands'
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 31, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 41, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//build_in/_base.py", line 102, in process
    page.update()
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/page.py", line 289, in update
    r = self.__update(self)
        ^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/page.py", line 416, in __update
    commands, added_controls, removed_controls = self.__prepare_update(*controls)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/page.py", line 438, in __prepare_update
    control.build_update_commands(
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/control.py", line 384, in build_update_commands
    ctrl.build_update_commands(
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/control.py", line 384, in build_update_commands
    ctrl.build_update_commands(
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/control.py", line 367, in build_update_commands
    innerCmds = ctrl._build_add_commands(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/flet_core/control.py", line 451, in _build_add_commands
    childCmd = control._build_add_commands(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute '_build_add_commands'
2023-12-05 22:37:45,269 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:37:45,270 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/MXNdnLGNFJ
2023-12-05 22:37:45,270 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/MXNdnLGNFJ
2023-12-05 22:37:45,270 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:37:45,270 - INFO - Starting Flet View app...
2023-12-05 22:37:45,270 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:37:45,485 - INFO - Session started: 
2023-12-05 22:46:27,430 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:46:27,431 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/DNqwmpVRTG
2023-12-05 22:46:27,431 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/DNqwmpVRTG
2023-12-05 22:46:27,431 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:46:27,431 - INFO - Starting Flet View app...
2023-12-05 22:46:27,431 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:46:27,637 - INFO - Session started: 
2023-12-05 22:51:49,998 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:51:49,999 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/uVtVJFobnk
2023-12-05 22:51:49,999 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/uVtVJFobnk
2023-12-05 22:51:49,999 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:51:50,000 - INFO - Starting Flet View app...
2023-12-05 22:51:50,000 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:51:50,214 - INFO - Session started: 
2023-12-05 22:58:58,578 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 22:58:58,579 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/oWYJcfXCpN
2023-12-05 22:58:58,579 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/oWYJcfXCpN
2023-12-05 22:58:58,579 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 22:58:58,579 - INFO - Starting Flet View app...
2023-12-05 22:58:58,580 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 22:58:58,792 - INFO - Session started: 
2023-12-05 23:02:56,045 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 23:02:56,046 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/MuojpIhAUJ
2023-12-05 23:02:56,047 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/MuojpIhAUJ
2023-12-05 23:02:56,047 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 23:02:56,047 - INFO - Starting Flet View app...
2023-12-05 23:02:56,047 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 23:02:56,267 - INFO - Session started: 
2023-12-05 23:03:12,128 - ERROR - Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 32, in run
    data = icls._run_plugin(plugin, data, **{**icls.context, **kwargs})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plug.py", line 42, in _run_plugin
    return plugin.process(data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/app/plugins//plugin_market.py", line 25, in process
    self.data = resp.json()
                ^^^^^^^^^^^
  File "/Users/yohoyes/projects/pythons/plugins-learn/plugin-base/venv/lib/python3.11/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-12-05 23:15:04,024 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-05 23:15:04,025 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/QNhlftOMzb
2023-12-05 23:15:04,026 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/QNhlftOMzb
2023-12-05 23:15:04,026 - INFO - Connected to Flet app and handling user sessions...
2023-12-05 23:15:04,026 - INFO - Starting Flet View app...
2023-12-05 23:15:04,026 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-05 23:15:04,300 - INFO - Session started: 
2023-12-06 00:05:12,033 - INFO - Assets path configured: /Users/yohoyes/projects/pythons/plugins-learn/plugin-base/assets
2023-12-06 00:05:12,034 - INFO - Starting up UDS server on /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/HEWiTHkBUJ
2023-12-06 00:05:12,034 - INFO - App URL: /var/folders/83/ppd8pjs94l7910j149k3h8kh0000gn/T/HEWiTHkBUJ
2023-12-06 00:05:12,034 - INFO - Connected to Flet app and handling user sessions...
2023-12-06 00:05:12,034 - INFO - Starting Flet View app...
2023-12-06 00:05:12,034 - INFO - Flet View found in: /Users/yohoyes/.flet/bin/flet-0.14.0
2023-12-06 00:05:12,290 - INFO - Session started: 
2023-12-06 00:05:14,288 - INFO - Started server process [85335]
2023-12-06 00:05:14,289 - INFO - Waiting for application startup.
2023-12-06 00:05:14,289 - INFO - Application startup complete.
2023-12-06 00:05:14,290 - INFO - Uvicorn running on http://0.0.0.0:36909 (Press CTRL+C to quit)
